### ISSUE TITLE
Special characters and length of passwords

### ISSUE THREAD

**Issue by JulPx** [andreacomo/wp-htpasswd-generator#1]
Hello and thanks for your plugin.

I've noted a few issues with the password generation:
- First, it seems that the encoding doesn't accept special characters from WordPress (such as é, è, à, etc...) and the authentication fails on the distant server.
- My second problem is linked to the password length: one can authenticate himself by giving the first 8 characters of the password only (eg in the .htaccess window, the user User with the password Password1234 can log in by typing Password, or Password0000, or PasswordMoreTextHere, etc...)

I would greatly appreciate your help,
JulPx

**Comment by andreacomo** [comment]
Hello and thank you for your warning. I'll check them out this weekend

**Comment by andreacomo** [comment]
Hi. I just released version 1.1.2: I fixed password length issue by changing encryption algorithm, but I cannot replicate accent problem (it's work for me). Can you try if it's working for you now? Maybe new algorithm resolves your first issue.

**Comment by JulPx** [comment]
Hello and thank you for quickly solving this password length problem !
About the special characters, I tried connecting with Chrome and it works fine for passwords containing certain characters like é - but not ô. I still can't log in using Safari...

JulPx

[Edit] precision

**Comment by andreacomo** [comment]
Hello,
I made some research about authentication header exchanged with server: it looks like hashed token in request header is generated in different way between Chrome and Safari (or Firefox). 
Searching on internet, it turned out that there's no standard on password hashing for non-ASCII chars by browser (http://stackoverflow.com/questions/702629/utf-8-characters-mangled-in-http-basic-auth-username), so I don't think I can solve it. 
Any suggestion?

**Comment by JulPx** [comment]
I also came accross these links. Thank you very much for searching !

JulPx

**Comment by andreacomo** [comment]
I can consider issue closed. Thanks for your collaboration
